// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// createSimilarityMat
arma::mat createSimilarityMat(arma::umat allocations);
RcppExport SEXP _batchmix_createSimilarityMat(SEXP allocationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type allocations(allocationsSEXP);
    rcpp_result_gen = Rcpp::wrap(createSimilarityMat(allocations));
    return rcpp_result_gen;
END_RCPP
}
// sampleLKJCorrelationMatrix
arma::mat sampleLKJCorrelationMatrix(arma::uword P, double eta);
RcppExport SEXP _batchmix_sampleLKJCorrelationMatrix(SEXP PSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleLKJCorrelationMatrix(P, eta));
    return rcpp_result_gen;
END_RCPP
}
// squaredExponentialKernel
arma::mat squaredExponentialKernel(arma::vec x, double tau2, double length_scale, double jitter);
RcppExport SEXP _batchmix_squaredExponentialKernel(SEXP xSEXP, SEXP tau2SEXP, SEXP length_scaleSEXP, SEXP jitterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type length_scale(length_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type jitter(jitterSEXP);
    rcpp_result_gen = Rcpp::wrap(squaredExponentialKernel(x, tau2, length_scale, jitter));
    return rcpp_result_gen;
END_RCPP
}
// maternKernel32
arma::mat maternKernel32(arma::vec x, double tau2, double length_scale, double jitter);
RcppExport SEXP _batchmix_maternKernel32(SEXP xSEXP, SEXP tau2SEXP, SEXP length_scaleSEXP, SEXP jitterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type length_scale(length_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type jitter(jitterSEXP);
    rcpp_result_gen = Rcpp::wrap(maternKernel32(x, tau2, length_scale, jitter));
    return rcpp_result_gen;
END_RCPP
}
// multinomialLogitLogLik
double multinomialLogitLogLik(arma::vec eta, arma::vec eta_other_sum, arma::vec class_counts_j, arma::vec class_counts_total);
RcppExport SEXP _batchmix_multinomialLogitLogLik(SEXP etaSEXP, SEXP eta_other_sumSEXP, SEXP class_counts_jSEXP, SEXP class_counts_totalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta_other_sum(eta_other_sumSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type class_counts_j(class_counts_jSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type class_counts_total(class_counts_totalSEXP);
    rcpp_result_gen = Rcpp::wrap(multinomialLogitLogLik(eta, eta_other_sum, class_counts_j, class_counts_total));
    return rcpp_result_gen;
END_RCPP
}
// multinomialLogitGPLogKernel
double multinomialLogitGPLogKernel(arma::vec eta, arma::vec eta_other_sum, arma::vec class_counts_j, arma::vec class_counts_total, arma::mat gp_chol, double beta);
RcppExport SEXP _batchmix_multinomialLogitGPLogKernel(SEXP etaSEXP, SEXP eta_other_sumSEXP, SEXP class_counts_jSEXP, SEXP class_counts_totalSEXP, SEXP gp_cholSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta_other_sum(eta_other_sumSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type class_counts_j(class_counts_jSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type class_counts_total(class_counts_totalSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gp_chol(gp_cholSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(multinomialLogitGPLogKernel(eta, eta_other_sum, class_counts_j, class_counts_total, gp_chol, beta));
    return rcpp_result_gen;
END_RCPP
}
// buildCorrelationCholeskyFromZ
arma::mat buildCorrelationCholeskyFromZ(arma::mat Z, arma::uword P);
RcppExport SEXP _batchmix_buildCorrelationCholeskyFromZ(SEXP ZSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(buildCorrelationCholeskyFromZ(Z, P));
    return rcpp_result_gen;
END_RCPP
}
// choleskyToPartialCorrelations
arma::mat choleskyToPartialCorrelations(arma::mat L, arma::uword P);
RcppExport SEXP _batchmix_choleskyToPartialCorrelations(SEXP LSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(choleskyToPartialCorrelations(L, P));
    return rcpp_result_gen;
END_RCPP
}
// logJacobianZToR
double logJacobianZToR(arma::mat Z, arma::uword P);
RcppExport SEXP _batchmix_logJacobianZToR(SEXP ZSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(logJacobianZToR(Z, P));
    return rcpp_result_gen;
END_RCPP
}
// robbinsMonroUpdate
double robbinsMonroUpdate(double window, double acceptance_rate, double target_rate, double n, double step_scale, double kappa);
RcppExport SEXP _batchmix_robbinsMonroUpdate(SEXP windowSEXP, SEXP acceptance_rateSEXP, SEXP target_rateSEXP, SEXP nSEXP, SEXP step_scaleSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type acceptance_rate(acceptance_rateSEXP);
    Rcpp::traits::input_parameter< double >::type target_rate(target_rateSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type step_scale(step_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(robbinsMonroUpdate(window, acceptance_rate, target_rate, n, step_scale, kappa));
    return rcpp_result_gen;
END_RCPP
}
// diagRSigmaOnlyChain2
Rcpp::List diagRSigmaOnlyChain2(arma::mat X, double rho_true, arma::uword n_iter, double r_pw, double sigma_pw);
RcppExport SEXP _batchmix_diagRSigmaOnlyChain2(SEXP XSEXP, SEXP rho_trueSEXP, SEXP n_iterSEXP, SEXP r_pwSEXP, SEXP sigma_pwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type rho_true(rho_trueSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type r_pw(r_pwSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_pw(sigma_pwSEXP);
    rcpp_result_gen = Rcpp::wrap(diagRSigmaOnlyChain2(X, rho_true, n_iter, r_pw, sigma_pw));
    return rcpp_result_gen;
END_RCPP
}
// gammaLogLikelihood
double gammaLogLikelihood(double x, double shape, double rate);
RcppExport SEXP _batchmix_gammaLogLikelihood(SEXP xSEXP, SEXP shapeSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(gammaLogLikelihood(x, shape, rate));
    return rcpp_result_gen;
END_RCPP
}
// invGammaLogLikelihood
double invGammaLogLikelihood(double x, double shape, double scale);
RcppExport SEXP _batchmix_invGammaLogLikelihood(SEXP xSEXP, SEXP shapeSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(invGammaLogLikelihood(x, shape, scale));
    return rcpp_result_gen;
END_RCPP
}
// wishartLogLikelihood
double wishartLogLikelihood(arma::mat X, arma::mat V, double n, arma::uword P);
RcppExport SEXP _batchmix_wishartLogLikelihood(SEXP XSEXP, SEXP VSEXP, SEXP nSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(wishartLogLikelihood(X, V, n, P));
    return rcpp_result_gen;
END_RCPP
}
// invWishartLogLikelihood
double invWishartLogLikelihood(arma::mat X, arma::mat Psi, double nu, arma::uword P);
RcppExport SEXP _batchmix_invWishartLogLikelihood(SEXP XSEXP, SEXP PsiSEXP, SEXP nuSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(invWishartLogLikelihood(X, Psi, nu, P));
    return rcpp_result_gen;
END_RCPP
}
// lkjLogLikelihood
double lkjLogLikelihood(arma::mat R, double eta);
RcppExport SEXP _batchmix_lkjLogLikelihood(SEXP RSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(lkjLogLikelihood(R, eta));
    return rcpp_result_gen;
END_RCPP
}
// sampleSemisupervisedMVN
Rcpp::List sampleSemisupervisedMVN(arma::mat X, arma::uword K, arma::uword B, arma::uvec labels, arma::uvec batch_vec, arma::uvec fixed, double mu_proposal_window, double cov_proposal_window, double m_proposal_window, double S_proposal_window, arma::uword n_iter, arma::uword thin, arma::vec concentration, double m_scale, double rho, double theta, arma::mat initial_mu, arma::cube initial_cov, arma::mat initial_m, arma::mat initial_S, bool mu_initialised, bool cov_initialised, bool m_initialised, bool S_initialised, bool sample_m_scale, bool auto_tune, arma::uword n_burn, bool include_interaction, double gamma_proposal_window, double a_gamma, double b_gamma, arma::uword weight_prior_type, arma::vec batch_coordinates, double gp_tau2, double gp_length_scale, double eta_proposal_window, bool sample_gp_hyperparameters, double gp_hyperparameter_proposal_window, double pp_tau2_shape, double pp_tau2_rate, double pp_mu_prior_sd);
RcppExport SEXP _batchmix_sampleSemisupervisedMVN(SEXP XSEXP, SEXP KSEXP, SEXP BSEXP, SEXP labelsSEXP, SEXP batch_vecSEXP, SEXP fixedSEXP, SEXP mu_proposal_windowSEXP, SEXP cov_proposal_windowSEXP, SEXP m_proposal_windowSEXP, SEXP S_proposal_windowSEXP, SEXP n_iterSEXP, SEXP thinSEXP, SEXP concentrationSEXP, SEXP m_scaleSEXP, SEXP rhoSEXP, SEXP thetaSEXP, SEXP initial_muSEXP, SEXP initial_covSEXP, SEXP initial_mSEXP, SEXP initial_SSEXP, SEXP mu_initialisedSEXP, SEXP cov_initialisedSEXP, SEXP m_initialisedSEXP, SEXP S_initialisedSEXP, SEXP sample_m_scaleSEXP, SEXP auto_tuneSEXP, SEXP n_burnSEXP, SEXP include_interactionSEXP, SEXP gamma_proposal_windowSEXP, SEXP a_gammaSEXP, SEXP b_gammaSEXP, SEXP weight_prior_typeSEXP, SEXP batch_coordinatesSEXP, SEXP gp_tau2SEXP, SEXP gp_length_scaleSEXP, SEXP eta_proposal_windowSEXP, SEXP sample_gp_hyperparametersSEXP, SEXP gp_hyperparameter_proposal_windowSEXP, SEXP pp_tau2_shapeSEXP, SEXP pp_tau2_rateSEXP, SEXP pp_mu_prior_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type batch_vec(batch_vecSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< double >::type mu_proposal_window(mu_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type cov_proposal_window(cov_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type m_proposal_window(m_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type S_proposal_window(S_proposal_windowSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type concentration(concentrationSEXP);
    Rcpp::traits::input_parameter< double >::type m_scale(m_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type initial_mu(initial_muSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type initial_cov(initial_covSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type initial_m(initial_mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type initial_S(initial_SSEXP);
    Rcpp::traits::input_parameter< bool >::type mu_initialised(mu_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type cov_initialised(cov_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type m_initialised(m_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type S_initialised(S_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_m_scale(sample_m_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type auto_tune(auto_tuneSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< bool >::type include_interaction(include_interactionSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_proposal_window(gamma_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma(a_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma(b_gammaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type weight_prior_type(weight_prior_typeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type batch_coordinates(batch_coordinatesSEXP);
    Rcpp::traits::input_parameter< double >::type gp_tau2(gp_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type gp_length_scale(gp_length_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type eta_proposal_window(eta_proposal_windowSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_gp_hyperparameters(sample_gp_hyperparametersSEXP);
    Rcpp::traits::input_parameter< double >::type gp_hyperparameter_proposal_window(gp_hyperparameter_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type pp_tau2_shape(pp_tau2_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type pp_tau2_rate(pp_tau2_rateSEXP);
    Rcpp::traits::input_parameter< double >::type pp_mu_prior_sd(pp_mu_prior_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleSemisupervisedMVN(X, K, B, labels, batch_vec, fixed, mu_proposal_window, cov_proposal_window, m_proposal_window, S_proposal_window, n_iter, thin, concentration, m_scale, rho, theta, initial_mu, initial_cov, initial_m, initial_S, mu_initialised, cov_initialised, m_initialised, S_initialised, sample_m_scale, auto_tune, n_burn, include_interaction, gamma_proposal_window, a_gamma, b_gamma, weight_prior_type, batch_coordinates, gp_tau2, gp_length_scale, eta_proposal_window, sample_gp_hyperparameters, gp_hyperparameter_proposal_window, pp_tau2_shape, pp_tau2_rate, pp_mu_prior_sd));
    return rcpp_result_gen;
END_RCPP
}
// sampleSemisupervisedMVNMixed
Rcpp::List sampleSemisupervisedMVNMixed(arma::mat X, arma::uword K, arma::uword B, arma::uvec labels, arma::uvec batch_vec, arma::uvec fixed, arma::uvec column_type, arma::umat censor_code, double mu_proposal_window, double r_proposal_window, double sigma_proposal_window, double m_proposal_window, double S_proposal_window, arma::uword n_iter, arma::uword thin, arma::vec concentration, double m_scale, double rho, double theta, double eta, bool sample_m_scale, bool auto_tune, arma::uword n_burn, bool include_interaction, double gamma_proposal_window, double a_gamma, double b_gamma, arma::uword weight_prior_type, arma::vec batch_coordinates, double gp_tau2, double gp_length_scale, double eta_proposal_window, bool sample_gp_hyperparameters, double gp_hyperparameter_proposal_window, double pp_tau2_shape, double pp_tau2_rate, double pp_mu_prior_sd);
RcppExport SEXP _batchmix_sampleSemisupervisedMVNMixed(SEXP XSEXP, SEXP KSEXP, SEXP BSEXP, SEXP labelsSEXP, SEXP batch_vecSEXP, SEXP fixedSEXP, SEXP column_typeSEXP, SEXP censor_codeSEXP, SEXP mu_proposal_windowSEXP, SEXP r_proposal_windowSEXP, SEXP sigma_proposal_windowSEXP, SEXP m_proposal_windowSEXP, SEXP S_proposal_windowSEXP, SEXP n_iterSEXP, SEXP thinSEXP, SEXP concentrationSEXP, SEXP m_scaleSEXP, SEXP rhoSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP sample_m_scaleSEXP, SEXP auto_tuneSEXP, SEXP n_burnSEXP, SEXP include_interactionSEXP, SEXP gamma_proposal_windowSEXP, SEXP a_gammaSEXP, SEXP b_gammaSEXP, SEXP weight_prior_typeSEXP, SEXP batch_coordinatesSEXP, SEXP gp_tau2SEXP, SEXP gp_length_scaleSEXP, SEXP eta_proposal_windowSEXP, SEXP sample_gp_hyperparametersSEXP, SEXP gp_hyperparameter_proposal_windowSEXP, SEXP pp_tau2_shapeSEXP, SEXP pp_tau2_rateSEXP, SEXP pp_mu_prior_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type batch_vec(batch_vecSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type column_type(column_typeSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type censor_code(censor_codeSEXP);
    Rcpp::traits::input_parameter< double >::type mu_proposal_window(mu_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type r_proposal_window(r_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_proposal_window(sigma_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type m_proposal_window(m_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type S_proposal_window(S_proposal_windowSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type concentration(concentrationSEXP);
    Rcpp::traits::input_parameter< double >::type m_scale(m_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_m_scale(sample_m_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type auto_tune(auto_tuneSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< bool >::type include_interaction(include_interactionSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_proposal_window(gamma_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma(a_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma(b_gammaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type weight_prior_type(weight_prior_typeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type batch_coordinates(batch_coordinatesSEXP);
    Rcpp::traits::input_parameter< double >::type gp_tau2(gp_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type gp_length_scale(gp_length_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type eta_proposal_window(eta_proposal_windowSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_gp_hyperparameters(sample_gp_hyperparametersSEXP);
    Rcpp::traits::input_parameter< double >::type gp_hyperparameter_proposal_window(gp_hyperparameter_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type pp_tau2_shape(pp_tau2_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type pp_tau2_rate(pp_tau2_rateSEXP);
    Rcpp::traits::input_parameter< double >::type pp_mu_prior_sd(pp_mu_prior_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleSemisupervisedMVNMixed(X, K, B, labels, batch_vec, fixed, column_type, censor_code, mu_proposal_window, r_proposal_window, sigma_proposal_window, m_proposal_window, S_proposal_window, n_iter, thin, concentration, m_scale, rho, theta, eta, sample_m_scale, auto_tune, n_burn, include_interaction, gamma_proposal_window, a_gamma, b_gamma, weight_prior_type, batch_coordinates, gp_tau2, gp_length_scale, eta_proposal_window, sample_gp_hyperparameters, gp_hyperparameter_proposal_window, pp_tau2_shape, pp_tau2_rate, pp_mu_prior_sd));
    return rcpp_result_gen;
END_RCPP
}
// sampleSemisupervisedMVNSeparationStrategy
Rcpp::List sampleSemisupervisedMVNSeparationStrategy(arma::mat X, arma::uword K, arma::uword B, arma::uvec labels, arma::uvec batch_vec, arma::uvec fixed, double mu_proposal_window, double r_proposal_window, double sigma_proposal_window, double m_proposal_window, double S_proposal_window, arma::uword n_iter, arma::uword thin, arma::vec concentration, double m_scale, double rho, double theta, arma::mat initial_mu, arma::cube initial_cov, arma::mat initial_m, arma::mat initial_S, bool mu_initialised, bool cov_initialised, bool m_initialised, bool S_initialised, bool sample_m_scale, double eta, bool auto_tune, arma::uword n_burn, bool include_interaction, double gamma_proposal_window, double a_gamma, double b_gamma, arma::uword weight_prior_type, arma::vec batch_coordinates, double gp_tau2, double gp_length_scale, double eta_proposal_window, bool sample_gp_hyperparameters, double gp_hyperparameter_proposal_window, double pp_tau2_shape, double pp_tau2_rate, double pp_mu_prior_sd);
RcppExport SEXP _batchmix_sampleSemisupervisedMVNSeparationStrategy(SEXP XSEXP, SEXP KSEXP, SEXP BSEXP, SEXP labelsSEXP, SEXP batch_vecSEXP, SEXP fixedSEXP, SEXP mu_proposal_windowSEXP, SEXP r_proposal_windowSEXP, SEXP sigma_proposal_windowSEXP, SEXP m_proposal_windowSEXP, SEXP S_proposal_windowSEXP, SEXP n_iterSEXP, SEXP thinSEXP, SEXP concentrationSEXP, SEXP m_scaleSEXP, SEXP rhoSEXP, SEXP thetaSEXP, SEXP initial_muSEXP, SEXP initial_covSEXP, SEXP initial_mSEXP, SEXP initial_SSEXP, SEXP mu_initialisedSEXP, SEXP cov_initialisedSEXP, SEXP m_initialisedSEXP, SEXP S_initialisedSEXP, SEXP sample_m_scaleSEXP, SEXP etaSEXP, SEXP auto_tuneSEXP, SEXP n_burnSEXP, SEXP include_interactionSEXP, SEXP gamma_proposal_windowSEXP, SEXP a_gammaSEXP, SEXP b_gammaSEXP, SEXP weight_prior_typeSEXP, SEXP batch_coordinatesSEXP, SEXP gp_tau2SEXP, SEXP gp_length_scaleSEXP, SEXP eta_proposal_windowSEXP, SEXP sample_gp_hyperparametersSEXP, SEXP gp_hyperparameter_proposal_windowSEXP, SEXP pp_tau2_shapeSEXP, SEXP pp_tau2_rateSEXP, SEXP pp_mu_prior_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type batch_vec(batch_vecSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< double >::type mu_proposal_window(mu_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type r_proposal_window(r_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_proposal_window(sigma_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type m_proposal_window(m_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type S_proposal_window(S_proposal_windowSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type concentration(concentrationSEXP);
    Rcpp::traits::input_parameter< double >::type m_scale(m_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type initial_mu(initial_muSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type initial_cov(initial_covSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type initial_m(initial_mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type initial_S(initial_SSEXP);
    Rcpp::traits::input_parameter< bool >::type mu_initialised(mu_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type cov_initialised(cov_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type m_initialised(m_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type S_initialised(S_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_m_scale(sample_m_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< bool >::type auto_tune(auto_tuneSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< bool >::type include_interaction(include_interactionSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_proposal_window(gamma_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma(a_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma(b_gammaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type weight_prior_type(weight_prior_typeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type batch_coordinates(batch_coordinatesSEXP);
    Rcpp::traits::input_parameter< double >::type gp_tau2(gp_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type gp_length_scale(gp_length_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type eta_proposal_window(eta_proposal_windowSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_gp_hyperparameters(sample_gp_hyperparametersSEXP);
    Rcpp::traits::input_parameter< double >::type gp_hyperparameter_proposal_window(gp_hyperparameter_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type pp_tau2_shape(pp_tau2_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type pp_tau2_rate(pp_tau2_rateSEXP);
    Rcpp::traits::input_parameter< double >::type pp_mu_prior_sd(pp_mu_prior_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleSemisupervisedMVNSeparationStrategy(X, K, B, labels, batch_vec, fixed, mu_proposal_window, r_proposal_window, sigma_proposal_window, m_proposal_window, S_proposal_window, n_iter, thin, concentration, m_scale, rho, theta, initial_mu, initial_cov, initial_m, initial_S, mu_initialised, cov_initialised, m_initialised, S_initialised, sample_m_scale, eta, auto_tune, n_burn, include_interaction, gamma_proposal_window, a_gamma, b_gamma, weight_prior_type, batch_coordinates, gp_tau2, gp_length_scale, eta_proposal_window, sample_gp_hyperparameters, gp_hyperparameter_proposal_window, pp_tau2_shape, pp_tau2_rate, pp_mu_prior_sd));
    return rcpp_result_gen;
END_RCPP
}
// sampleSemisupervisedMVT
Rcpp::List sampleSemisupervisedMVT(arma::mat X, arma::uword K, arma::uword B, arma::uvec labels, arma::uvec batch_vec, arma::uvec fixed, double mu_proposal_window, double cov_proposal_window, double m_proposal_window, double S_proposal_window, double t_df_proposal_window, arma::uword n_iter, arma::uword thin, arma::vec concentration, double m_scale, double rho, double theta, arma::mat initial_mu, arma::cube initial_cov, arma::vec initial_df, arma::mat initial_m, arma::mat initial_S, bool mu_initialised, bool cov_initialised, bool df_initialised, bool m_initialised, bool S_initialised, bool sample_m_scale, bool auto_tune, arma::uword n_burn, bool include_interaction, double gamma_proposal_window, double a_gamma, double b_gamma, arma::uword weight_prior_type, arma::vec batch_coordinates, double gp_tau2, double gp_length_scale, double eta_proposal_window, bool sample_gp_hyperparameters, double gp_hyperparameter_proposal_window, double pp_tau2_shape, double pp_tau2_rate, double pp_mu_prior_sd);
RcppExport SEXP _batchmix_sampleSemisupervisedMVT(SEXP XSEXP, SEXP KSEXP, SEXP BSEXP, SEXP labelsSEXP, SEXP batch_vecSEXP, SEXP fixedSEXP, SEXP mu_proposal_windowSEXP, SEXP cov_proposal_windowSEXP, SEXP m_proposal_windowSEXP, SEXP S_proposal_windowSEXP, SEXP t_df_proposal_windowSEXP, SEXP n_iterSEXP, SEXP thinSEXP, SEXP concentrationSEXP, SEXP m_scaleSEXP, SEXP rhoSEXP, SEXP thetaSEXP, SEXP initial_muSEXP, SEXP initial_covSEXP, SEXP initial_dfSEXP, SEXP initial_mSEXP, SEXP initial_SSEXP, SEXP mu_initialisedSEXP, SEXP cov_initialisedSEXP, SEXP df_initialisedSEXP, SEXP m_initialisedSEXP, SEXP S_initialisedSEXP, SEXP sample_m_scaleSEXP, SEXP auto_tuneSEXP, SEXP n_burnSEXP, SEXP include_interactionSEXP, SEXP gamma_proposal_windowSEXP, SEXP a_gammaSEXP, SEXP b_gammaSEXP, SEXP weight_prior_typeSEXP, SEXP batch_coordinatesSEXP, SEXP gp_tau2SEXP, SEXP gp_length_scaleSEXP, SEXP eta_proposal_windowSEXP, SEXP sample_gp_hyperparametersSEXP, SEXP gp_hyperparameter_proposal_windowSEXP, SEXP pp_tau2_shapeSEXP, SEXP pp_tau2_rateSEXP, SEXP pp_mu_prior_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type batch_vec(batch_vecSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type fixed(fixedSEXP);
    Rcpp::traits::input_parameter< double >::type mu_proposal_window(mu_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type cov_proposal_window(cov_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type m_proposal_window(m_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type S_proposal_window(S_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type t_df_proposal_window(t_df_proposal_windowSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type concentration(concentrationSEXP);
    Rcpp::traits::input_parameter< double >::type m_scale(m_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type initial_mu(initial_muSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type initial_cov(initial_covSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type initial_df(initial_dfSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type initial_m(initial_mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type initial_S(initial_SSEXP);
    Rcpp::traits::input_parameter< bool >::type mu_initialised(mu_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type cov_initialised(cov_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type df_initialised(df_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type m_initialised(m_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type S_initialised(S_initialisedSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_m_scale(sample_m_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type auto_tune(auto_tuneSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< bool >::type include_interaction(include_interactionSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_proposal_window(gamma_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma(a_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma(b_gammaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type weight_prior_type(weight_prior_typeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type batch_coordinates(batch_coordinatesSEXP);
    Rcpp::traits::input_parameter< double >::type gp_tau2(gp_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type gp_length_scale(gp_length_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type eta_proposal_window(eta_proposal_windowSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_gp_hyperparameters(sample_gp_hyperparametersSEXP);
    Rcpp::traits::input_parameter< double >::type gp_hyperparameter_proposal_window(gp_hyperparameter_proposal_windowSEXP);
    Rcpp::traits::input_parameter< double >::type pp_tau2_shape(pp_tau2_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type pp_tau2_rate(pp_tau2_rateSEXP);
    Rcpp::traits::input_parameter< double >::type pp_mu_prior_sd(pp_mu_prior_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(sampleSemisupervisedMVT(X, K, B, labels, batch_vec, fixed, mu_proposal_window, cov_proposal_window, m_proposal_window, S_proposal_window, t_df_proposal_window, n_iter, thin, concentration, m_scale, rho, theta, initial_mu, initial_cov, initial_df, initial_m, initial_S, mu_initialised, cov_initialised, df_initialised, m_initialised, S_initialised, sample_m_scale, auto_tune, n_burn, include_interaction, gamma_proposal_window, a_gamma, b_gamma, weight_prior_type, batch_coordinates, gp_tau2, gp_length_scale, eta_proposal_window, sample_gp_hyperparameters, gp_hyperparameter_proposal_window, pp_tau2_shape, pp_tau2_rate, pp_mu_prior_sd));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_batchmix_createSimilarityMat", (DL_FUNC) &_batchmix_createSimilarityMat, 1},
    {"_batchmix_sampleLKJCorrelationMatrix", (DL_FUNC) &_batchmix_sampleLKJCorrelationMatrix, 2},
    {"_batchmix_squaredExponentialKernel", (DL_FUNC) &_batchmix_squaredExponentialKernel, 4},
    {"_batchmix_maternKernel32", (DL_FUNC) &_batchmix_maternKernel32, 4},
    {"_batchmix_multinomialLogitLogLik", (DL_FUNC) &_batchmix_multinomialLogitLogLik, 4},
    {"_batchmix_multinomialLogitGPLogKernel", (DL_FUNC) &_batchmix_multinomialLogitGPLogKernel, 6},
    {"_batchmix_buildCorrelationCholeskyFromZ", (DL_FUNC) &_batchmix_buildCorrelationCholeskyFromZ, 2},
    {"_batchmix_choleskyToPartialCorrelations", (DL_FUNC) &_batchmix_choleskyToPartialCorrelations, 2},
    {"_batchmix_logJacobianZToR", (DL_FUNC) &_batchmix_logJacobianZToR, 2},
    {"_batchmix_robbinsMonroUpdate", (DL_FUNC) &_batchmix_robbinsMonroUpdate, 6},
    {"_batchmix_diagRSigmaOnlyChain2", (DL_FUNC) &_batchmix_diagRSigmaOnlyChain2, 5},
    {"_batchmix_gammaLogLikelihood", (DL_FUNC) &_batchmix_gammaLogLikelihood, 3},
    {"_batchmix_invGammaLogLikelihood", (DL_FUNC) &_batchmix_invGammaLogLikelihood, 3},
    {"_batchmix_wishartLogLikelihood", (DL_FUNC) &_batchmix_wishartLogLikelihood, 4},
    {"_batchmix_invWishartLogLikelihood", (DL_FUNC) &_batchmix_invWishartLogLikelihood, 4},
    {"_batchmix_lkjLogLikelihood", (DL_FUNC) &_batchmix_lkjLogLikelihood, 2},
    {"_batchmix_sampleSemisupervisedMVN", (DL_FUNC) &_batchmix_sampleSemisupervisedMVN, 41},
    {"_batchmix_sampleSemisupervisedMVNMixed", (DL_FUNC) &_batchmix_sampleSemisupervisedMVNMixed, 37},
    {"_batchmix_sampleSemisupervisedMVNSeparationStrategy", (DL_FUNC) &_batchmix_sampleSemisupervisedMVNSeparationStrategy, 43},
    {"_batchmix_sampleSemisupervisedMVT", (DL_FUNC) &_batchmix_sampleSemisupervisedMVT, 44},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_batchmix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
